# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-01-24 23:36
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('wallet', models.FloatField(default=1000)),
            ],
            options={
                'db_table': 'service_account',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='configs')),
            ],
            options={
                'db_table': 'service_configfile',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='datahome')),
                ('size', models.FloatField(default=0)),
                ('times', models.IntegerField(default=0)),
                ('cbtype', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField()),
                ('verified', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_dataset',
            },
        ),
        migrations.CreateModel(
            name='DatasetServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipport', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'service_datasetserver',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipport', models.CharField(max_length=32)),
                ('cuda', models.IntegerField(default=0)),
                ('gputype', models.CharField(max_length=32)),
                ('memory', models.FloatField(default=0)),
                ('price', models.FloatField(default=20000)),
                ('lat', models.FloatField(default=22.93772)),
                ('lng', models.FloatField(default=113.38424)),
                ('nation', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('adcode', models.IntegerField(default=440113)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField()),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_gpu',
            },
        ),
        migrations.CreateModel(
            name='RoomDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipport', models.CharField(max_length=32)),
                ('max_memory', models.FloatField(default=1024)),
                ('message', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('running', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Dataset')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_roomdb',
            },
        ),
        migrations.AddField(
            model_name='gpu',
            name='rooms',
            field=models.ManyToManyField(to='room.RoomDB'),
        ),
        migrations.AddField(
            model_name='configfile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.RoomDB'),
        ),
        migrations.AddField(
            model_name='account',
            name='accessdataset',
            field=models.ManyToManyField(to='room.Dataset'),
        ),
        migrations.AddField(
            model_name='account',
            name='accessroom',
            field=models.ManyToManyField(to='room.RoomDB'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='locate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='room.RoomDB'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
